#!/bin/bash

set -e

cd underworld3
git stash
git pull
./compile.sh
cd ..

git clone --single-branch --branch main https://github.com/bknight1/diffusionDecayIngrowth.git

## This is not required for the conda-forge version of petsc but
## it is needed if we install the uw3_env dependencies

export PYTHONPATH=$CONDA_PREFIX/lib/ 

exec "$@"
